///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WL_Automation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WL_AutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7ff793f0-612e-446c-bf18-ffe4d283210d")]
    public partial class WL_AutomationRepository : RepoGenBaseFolder
    {
        static WL_AutomationRepository instance = new WL_AutomationRepository();
        WL_AutomationRepositoryFolders.SaucedemoAppFolder _saucedemo;

        /// <summary>
        /// Gets the singleton class instance representing the WL_AutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("7ff793f0-612e-446c-bf18-ffe4d283210d")]
        public static WL_AutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WL_AutomationRepository() 
            : base("WL_AutomationRepository", "/", null, 0, false, "7ff793f0-612e-446c-bf18-ffe4d283210d", ".\\RepositoryImages\\WL_AutomationRepository7ff793f0.rximgres")
        {
            _saucedemo = new WL_AutomationRepositoryFolders.SaucedemoAppFolder(this);
        }

#region Variables

        string _productName = "";

        /// <summary>
        /// Gets or sets the value of variable productName.
        /// </summary>
        [TestVariable("80d02ec6-3f1f-4052-95b3-d89cdcbaa22f")]
        public string productName
        {
            get { return _productName; }
            set { _productName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7ff793f0-612e-446c-bf18-ffe4d283210d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Saucedemo folder.
        /// </summary>
        [RepositoryFolder("e18c6ce5-62d0-454c-b225-9a9eb75d2716")]
        public virtual WL_AutomationRepositoryFolders.SaucedemoAppFolder Saucedemo
        {
            get { return _saucedemo; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WL_AutomationRepositoryFolders
    {
        /// <summary>
        /// The SaucedemoAppFolder folder.
        /// </summary>
        [RepositoryFolder("e18c6ce5-62d0-454c-b225-9a9eb75d2716")]
        public partial class SaucedemoAppFolder : RepoGenBaseFolder
        {
            WL_AutomationRepositoryFolders.LoginFolder _login;
            WL_AutomationRepositoryFolders.HeaderSectionFolder _headersection;
            WL_AutomationRepositoryFolders.ProductsFolder _products;
            WL_AutomationRepositoryFolders.CartDetailsFolder _cartdetails;
            WL_AutomationRepositoryFolders.CheckoutFolder _checkout;
            WL_AutomationRepositoryFolders.OverviewFolder _overview;
            WL_AutomationRepositoryFolders.PurchaseDoneFolder _purchasedone;
            WL_AutomationRepositoryFolders.MenuFolder _menu;

            /// <summary>
            /// Creates a new Saucedemo  folder.
            /// </summary>
            public SaucedemoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Saucedemo", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "e18c6ce5-62d0-454c-b225-9a9eb75d2716", "")
            {
                _login = new WL_AutomationRepositoryFolders.LoginFolder(this);
                _headersection = new WL_AutomationRepositoryFolders.HeaderSectionFolder(this);
                _products = new WL_AutomationRepositoryFolders.ProductsFolder(this);
                _cartdetails = new WL_AutomationRepositoryFolders.CartDetailsFolder(this);
                _checkout = new WL_AutomationRepositoryFolders.CheckoutFolder(this);
                _overview = new WL_AutomationRepositoryFolders.OverviewFolder(this);
                _purchasedone = new WL_AutomationRepositoryFolders.PurchaseDoneFolder(this);
                _menu = new WL_AutomationRepositoryFolders.MenuFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e18c6ce5-62d0-454c-b225-9a9eb75d2716")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e18c6ce5-62d0-454c-b225-9a9eb75d2716")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("8fd78915-b74e-4357-9ba0-0677ef5cfaaa")]
            public virtual WL_AutomationRepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }

            /// <summary>
            /// The HeaderSection folder.
            /// </summary>
            [RepositoryFolder("d0c373ab-92c7-47ab-9476-6854375066bc")]
            public virtual WL_AutomationRepositoryFolders.HeaderSectionFolder HeaderSection
            {
                get { return _headersection; }
            }

            /// <summary>
            /// The Products folder.
            /// </summary>
            [RepositoryFolder("76d7d152-c562-41b2-bb5e-d28a4ecefbaf")]
            public virtual WL_AutomationRepositoryFolders.ProductsFolder Products
            {
                get { return _products; }
            }

            /// <summary>
            /// The CartDetails folder.
            /// </summary>
            [RepositoryFolder("e069166f-354a-4cdf-a344-eb67520dd19c")]
            public virtual WL_AutomationRepositoryFolders.CartDetailsFolder CartDetails
            {
                get { return _cartdetails; }
            }

            /// <summary>
            /// The Checkout folder.
            /// </summary>
            [RepositoryFolder("aa4b8b25-7c5f-4372-8c69-49a5757459d0")]
            public virtual WL_AutomationRepositoryFolders.CheckoutFolder Checkout
            {
                get { return _checkout; }
            }

            /// <summary>
            /// The Overview folder.
            /// </summary>
            [RepositoryFolder("fb868e7e-32ac-434d-b394-6b9591dbea1d")]
            public virtual WL_AutomationRepositoryFolders.OverviewFolder Overview
            {
                get { return _overview; }
            }

            /// <summary>
            /// The PurchaseDone folder.
            /// </summary>
            [RepositoryFolder("7012e882-544c-4626-9eb3-0c3dd9361468")]
            public virtual WL_AutomationRepositoryFolders.PurchaseDoneFolder PurchaseDone
            {
                get { return _purchasedone; }
            }

            /// <summary>
            /// The Menu folder.
            /// </summary>
            [RepositoryFolder("6eb37da9-ff55-4cb7-8f83-420516acd984")]
            public virtual WL_AutomationRepositoryFolders.MenuFolder Menu
            {
                get { return _menu; }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("8fd78915-b74e-4357-9ba0-0677ef5cfaaa")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _username_inputInfo;
            RepoItemInfo _password_inputInfo;
            RepoItemInfo _login_buttonInfo;
            RepoItemInfo _loginlogo_divInfo;
            RepoItemInfo _loginwrapperinner_divInfo;
            RepoItemInfo _botcolumn_divInfo;
            RepoItemInfo _logincredentials_divInfo;
            RepoItemInfo _secretsauce_divInfo;
            RepoItemInfo _credentials_divInfo;
            RepoItemInfo _errormsg_divInfo;
            RepoItemInfo _errorcontainer_divInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "8fd78915-b74e-4357-9ba0-0677ef5cfaaa", "")
            {
                _username_inputInfo = new RepoItemInfo(this, "UserName_input", ".//input[#'user-name']", "", 30000, null, "988f4298-3153-4a8e-9076-44a45a4e0b1d");
                _password_inputInfo = new RepoItemInfo(this, "Password_input", ".//input[#'password']", "", 30000, null, "57110c14-b3fe-49e7-8a60-25d32759247e");
                _login_buttonInfo = new RepoItemInfo(this, "Login_button", ".//input[#'login-button']", "", 30000, null, "bc6aa3ff-3cc2-489c-8051-c6f6f9bd150e");
                _loginlogo_divInfo = new RepoItemInfo(this, "LoginLogo_div", ".//div[#'root']///div[@class='login_logo']", "", 30000, null, "71ef5762-4d02-4c74-83d5-595f0ae1caf4");
                _loginwrapperinner_divInfo = new RepoItemInfo(this, "LoginWrapperInner_div", ".//div[#'root']/div/div[2]/div[1]", "", 30000, null, "5860f108-54b4-4fad-8553-a8b618bc01a7");
                _botcolumn_divInfo = new RepoItemInfo(this, "BotColumn_div", ".//div[#'root']/div/div[2]/div[1]/div[@class='bot_column']", "", 30000, null, "90fa28e1-f47a-445b-aec3-6b73c6072ef2");
                _logincredentials_divInfo = new RepoItemInfo(this, "LoginCredentials_div", ".//div[#'root']/div/div[2]/div[2]/div", "", 30000, null, "1a19ce25-8a69-4f8a-83db-45c260b68a85");
                _secretsauce_divInfo = new RepoItemInfo(this, "SecretSauce_div", ".//div[#'root']/div/div[2]//div[@innertext='secret_sauce']", "", 30000, null, "cc891bca-8b29-4e8b-b5cd-2ef14a22b186");
                _credentials_divInfo = new RepoItemInfo(this, "Credentials_div", ".//div[#'login_credentials']", "", 30000, null, "ca37d117-0be8-4ae2-9efb-4696cb1d7fac");
                _errormsg_divInfo = new RepoItemInfo(this, "ErrorMsg_div", ".//div[#'login_button_container']/?/?/form[@action='https://www.saucedemo.com/']/?/?/h3[@innertext>'Epic sadface: Sorry, this']", "", 30000, null, "2865e80f-2453-4c48-b4d6-7d86c6bec766");
                _errorcontainer_divInfo = new RepoItemInfo(this, "ErrorContainer_div", ".//div[#'login_button_container']/?/?/form[@action='https://www.saucedemo.com/']/div[3]", "", 30000, null, "1b080728-0e2b-40d8-ae53-83501839ba0b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8fd78915-b74e-4357-9ba0-0677ef5cfaaa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName_input item.
            /// </summary>
            [RepositoryItem("988f4298-3153-4a8e-9076-44a45a4e0b1d")]
            public virtual Ranorex.InputTag UserName_input
            {
                get
                {
                    return _username_inputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName_input item info.
            /// </summary>
            [RepositoryItemInfo("988f4298-3153-4a8e-9076-44a45a4e0b1d")]
            public virtual RepoItemInfo UserName_inputInfo
            {
                get
                {
                    return _username_inputInfo;
                }
            }

            /// <summary>
            /// The Password_input item.
            /// </summary>
            [RepositoryItem("57110c14-b3fe-49e7-8a60-25d32759247e")]
            public virtual Ranorex.InputTag Password_input
            {
                get
                {
                    return _password_inputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password_input item info.
            /// </summary>
            [RepositoryItemInfo("57110c14-b3fe-49e7-8a60-25d32759247e")]
            public virtual RepoItemInfo Password_inputInfo
            {
                get
                {
                    return _password_inputInfo;
                }
            }

            /// <summary>
            /// The Login_button item.
            /// </summary>
            [RepositoryItem("bc6aa3ff-3cc2-489c-8051-c6f6f9bd150e")]
            public virtual Ranorex.InputTag Login_button
            {
                get
                {
                    return _login_buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login_button item info.
            /// </summary>
            [RepositoryItemInfo("bc6aa3ff-3cc2-489c-8051-c6f6f9bd150e")]
            public virtual RepoItemInfo Login_buttonInfo
            {
                get
                {
                    return _login_buttonInfo;
                }
            }

            /// <summary>
            /// The LoginLogo_div item.
            /// </summary>
            [RepositoryItem("71ef5762-4d02-4c74-83d5-595f0ae1caf4")]
            public virtual Ranorex.DivTag LoginLogo_div
            {
                get
                {
                    return _loginlogo_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginLogo_div item info.
            /// </summary>
            [RepositoryItemInfo("71ef5762-4d02-4c74-83d5-595f0ae1caf4")]
            public virtual RepoItemInfo LoginLogo_divInfo
            {
                get
                {
                    return _loginlogo_divInfo;
                }
            }

            /// <summary>
            /// The LoginWrapperInner_div item.
            /// </summary>
            [RepositoryItem("5860f108-54b4-4fad-8553-a8b618bc01a7")]
            public virtual Ranorex.DivTag LoginWrapperInner_div
            {
                get
                {
                    return _loginwrapperinner_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginWrapperInner_div item info.
            /// </summary>
            [RepositoryItemInfo("5860f108-54b4-4fad-8553-a8b618bc01a7")]
            public virtual RepoItemInfo LoginWrapperInner_divInfo
            {
                get
                {
                    return _loginwrapperinner_divInfo;
                }
            }

            /// <summary>
            /// The BotColumn_div item.
            /// </summary>
            [RepositoryItem("90fa28e1-f47a-445b-aec3-6b73c6072ef2")]
            public virtual Ranorex.DivTag BotColumn_div
            {
                get
                {
                    return _botcolumn_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BotColumn_div item info.
            /// </summary>
            [RepositoryItemInfo("90fa28e1-f47a-445b-aec3-6b73c6072ef2")]
            public virtual RepoItemInfo BotColumn_divInfo
            {
                get
                {
                    return _botcolumn_divInfo;
                }
            }

            /// <summary>
            /// The LoginCredentials_div item.
            /// </summary>
            [RepositoryItem("1a19ce25-8a69-4f8a-83db-45c260b68a85")]
            public virtual Ranorex.DivTag LoginCredentials_div
            {
                get
                {
                    return _logincredentials_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginCredentials_div item info.
            /// </summary>
            [RepositoryItemInfo("1a19ce25-8a69-4f8a-83db-45c260b68a85")]
            public virtual RepoItemInfo LoginCredentials_divInfo
            {
                get
                {
                    return _logincredentials_divInfo;
                }
            }

            /// <summary>
            /// The SecretSauce_div item.
            /// </summary>
            [RepositoryItem("cc891bca-8b29-4e8b-b5cd-2ef14a22b186")]
            public virtual Ranorex.DivTag SecretSauce_div
            {
                get
                {
                    return _secretsauce_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SecretSauce_div item info.
            /// </summary>
            [RepositoryItemInfo("cc891bca-8b29-4e8b-b5cd-2ef14a22b186")]
            public virtual RepoItemInfo SecretSauce_divInfo
            {
                get
                {
                    return _secretsauce_divInfo;
                }
            }

            /// <summary>
            /// The Credentials_div item.
            /// </summary>
            [RepositoryItem("ca37d117-0be8-4ae2-9efb-4696cb1d7fac")]
            public virtual Ranorex.DivTag Credentials_div
            {
                get
                {
                    return _credentials_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Credentials_div item info.
            /// </summary>
            [RepositoryItemInfo("ca37d117-0be8-4ae2-9efb-4696cb1d7fac")]
            public virtual RepoItemInfo Credentials_divInfo
            {
                get
                {
                    return _credentials_divInfo;
                }
            }

            /// <summary>
            /// The ErrorMsg_div item.
            /// </summary>
            [RepositoryItem("2865e80f-2453-4c48-b4d6-7d86c6bec766")]
            public virtual Ranorex.H3Tag ErrorMsg_div
            {
                get
                {
                    return _errormsg_divInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The ErrorMsg_div item info.
            /// </summary>
            [RepositoryItemInfo("2865e80f-2453-4c48-b4d6-7d86c6bec766")]
            public virtual RepoItemInfo ErrorMsg_divInfo
            {
                get
                {
                    return _errormsg_divInfo;
                }
            }

            /// <summary>
            /// The ErrorContainer_div item.
            /// </summary>
            [RepositoryItem("1b080728-0e2b-40d8-ae53-83501839ba0b")]
            public virtual Ranorex.DivTag ErrorContainer_div
            {
                get
                {
                    return _errorcontainer_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ErrorContainer_div item info.
            /// </summary>
            [RepositoryItemInfo("1b080728-0e2b-40d8-ae53-83501839ba0b")]
            public virtual RepoItemInfo ErrorContainer_divInfo
            {
                get
                {
                    return _errorcontainer_divInfo;
                }
            }
        }

        /// <summary>
        /// The HeaderSectionFolder folder.
        /// </summary>
        [RepositoryFolder("d0c373ab-92c7-47ab-9476-6854375066bc")]
        public partial class HeaderSectionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _header_divInfo;
            RepoItemInfo _applogo_divInfo;
            RepoItemInfo _menu_btnInfo;
            RepoItemInfo _shoppingcart_aInfo;

            /// <summary>
            /// Creates a new HeaderSection  folder.
            /// </summary>
            public HeaderSectionFolder(RepoGenBaseFolder parentFolder) :
                    base("HeaderSection", "", parentFolder, 0, null, false, "d0c373ab-92c7-47ab-9476-6854375066bc", "")
            {
                _header_divInfo = new RepoItemInfo(this, "Header_div", ".//div[#'header_container']/div[1]/div[2]", "", 30000, null, "92fad55b-d014-47af-afe4-a745f7af3bd6");
                _applogo_divInfo = new RepoItemInfo(this, "AppLogo_div", ".//div[#'header_container']/div[1]/div[2]/div", "", 30000, null, "18e055ce-89f5-41b9-b8fe-9f7407afb81e");
                _menu_btnInfo = new RepoItemInfo(this, "Menu_btn", ".//button[#'react-burger-menu-btn']", "", 30000, null, "bc37021f-ad65-4628-80d7-815557394e5d");
                _shoppingcart_aInfo = new RepoItemInfo(this, "ShoppingCart_a", ".//div[#'shopping_cart_container']/a", "", 30000, null, "47b576f4-ada9-457c-ab49-998b07a23657");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0c373ab-92c7-47ab-9476-6854375066bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Header_div item.
            /// </summary>
            [RepositoryItem("92fad55b-d014-47af-afe4-a745f7af3bd6")]
            public virtual Ranorex.DivTag Header_div
            {
                get
                {
                    return _header_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Header_div item info.
            /// </summary>
            [RepositoryItemInfo("92fad55b-d014-47af-afe4-a745f7af3bd6")]
            public virtual RepoItemInfo Header_divInfo
            {
                get
                {
                    return _header_divInfo;
                }
            }

            /// <summary>
            /// The AppLogo_div item.
            /// </summary>
            [RepositoryItem("18e055ce-89f5-41b9-b8fe-9f7407afb81e")]
            public virtual Ranorex.DivTag AppLogo_div
            {
                get
                {
                    return _applogo_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AppLogo_div item info.
            /// </summary>
            [RepositoryItemInfo("18e055ce-89f5-41b9-b8fe-9f7407afb81e")]
            public virtual RepoItemInfo AppLogo_divInfo
            {
                get
                {
                    return _applogo_divInfo;
                }
            }

            /// <summary>
            /// The Menu_btn item.
            /// </summary>
            [RepositoryItem("bc37021f-ad65-4628-80d7-815557394e5d")]
            public virtual Ranorex.ButtonTag Menu_btn
            {
                get
                {
                    return _menu_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Menu_btn item info.
            /// </summary>
            [RepositoryItemInfo("bc37021f-ad65-4628-80d7-815557394e5d")]
            public virtual RepoItemInfo Menu_btnInfo
            {
                get
                {
                    return _menu_btnInfo;
                }
            }

            /// <summary>
            /// The ShoppingCart_a item.
            /// </summary>
            [RepositoryItem("47b576f4-ada9-457c-ab49-998b07a23657")]
            public virtual Ranorex.ATag ShoppingCart_a
            {
                get
                {
                    return _shoppingcart_aInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ShoppingCart_a item info.
            /// </summary>
            [RepositoryItemInfo("47b576f4-ada9-457c-ab49-998b07a23657")]
            public virtual RepoItemInfo ShoppingCart_aInfo
            {
                get
                {
                    return _shoppingcart_aInfo;
                }
            }
        }

        /// <summary>
        /// The ProductsFolder folder.
        /// </summary>
        [RepositoryFolder("76d7d152-c562-41b2-bb5e-d28a4ecefbaf")]
        public partial class ProductsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _products_spanInfo;
            RepoItemInfo _productsort_selectInfo;
            RepoItemInfo _productitem_divInfo;
            RepoItemInfo _productimg_divInfo;
            RepoItemInfo _productname_divInfo;
            RepoItemInfo _productdescritpion_divInfo;
            RepoItemInfo _productprice_divInfo;
            RepoItemInfo _addproduct_btnInfo;
            RepoItemInfo _numitemscart_spanInfo;

            /// <summary>
            /// Creates a new Products  folder.
            /// </summary>
            public ProductsFolder(RepoGenBaseFolder parentFolder) :
                    base("Products", "", parentFolder, 0, null, false, "76d7d152-c562-41b2-bb5e-d28a4ecefbaf", "")
            {
                _products_spanInfo = new RepoItemInfo(this, "Products_span", ".//div[#'header_container']/?/?/span[@innertext='Products']", "", 30000, null, "f34044fd-cbe9-409a-8350-e7a0aa30a6c3");
                _productsort_selectInfo = new RepoItemInfo(this, "ProductSort_select", ".///select[@class='product_sort_container']", "", 30000, null, "975d7463-9074-4bf6-8d21-8b2340776e9e");
                _productitem_divInfo = new RepoItemInfo(this, "ProductItem_div", ".///div[@id='inventory_container']///div[@class='inventory_item']", "", 30000, null, "2d770580-0b3a-4636-a9e7-aba8fc7dd3ee");
                _productimg_divInfo = new RepoItemInfo(this, "ProductImg_div", ".///div[@class='inventory_item_img']/a/img[@alt=$productName]", "", 30000, null, "a40ac1b0-2323-4827-a924-6984842ec2f6");
                _productname_divInfo = new RepoItemInfo(this, "ProductName_div", ".///div[@id='inventory_container']///div[@class='inventory_item_name' and @innertext=$productName]", "", 30000, null, "53d93c6b-8cf2-45f7-b30c-64ccceb2e320");
                _productdescritpion_divInfo = new RepoItemInfo(this, "ProductDescritpion_div", ".///div[@id='inventory_container']///div[@class='inventory_item_name' and @innertext=$productName]/../../div[@class='inventory_item_desc']", "", 30000, null, "f6220996-0c38-4d0b-8270-d98dd595cf00");
                _productprice_divInfo = new RepoItemInfo(this, "ProductPrice_div", ".///div[@class='inventory_item_name' and @innertext=$productName]/../../../div[@class='pricebar']/div[@class='inventory_item_price']", "", 30000, null, "5f65492b-294f-44e3-9b43-64a427f324f8");
                _addproduct_btnInfo = new RepoItemInfo(this, "AddProduct_btn", ".///div[@class='inventory_item_name' and @innertext=$productName]/../../../div[@class='pricebar']//button[@class='btn btn_primary btn_small btn_inventory']", "", 30000, null, "d203cb1f-3811-4239-ac39-d17a2de11527");
                _numitemscart_spanInfo = new RepoItemInfo(this, "numItemsCart_span", ".//div[#'shopping_cart_container']/a/span[@class='shopping_cart_badge']", "", 30000, null, "48083637-a0ad-41ab-b409-3ff520452c5f");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("76d7d152-c562-41b2-bb5e-d28a4ecefbaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Products_span item.
            /// </summary>
            [RepositoryItem("f34044fd-cbe9-409a-8350-e7a0aa30a6c3")]
            public virtual Ranorex.SpanTag Products_span
            {
                get
                {
                    return _products_spanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Products_span item info.
            /// </summary>
            [RepositoryItemInfo("f34044fd-cbe9-409a-8350-e7a0aa30a6c3")]
            public virtual RepoItemInfo Products_spanInfo
            {
                get
                {
                    return _products_spanInfo;
                }
            }

            /// <summary>
            /// The ProductSort_select item.
            /// </summary>
            [RepositoryItem("975d7463-9074-4bf6-8d21-8b2340776e9e")]
            public virtual Ranorex.SelectTag ProductSort_select
            {
                get
                {
                    return _productsort_selectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ProductSort_select item info.
            /// </summary>
            [RepositoryItemInfo("975d7463-9074-4bf6-8d21-8b2340776e9e")]
            public virtual RepoItemInfo ProductSort_selectInfo
            {
                get
                {
                    return _productsort_selectInfo;
                }
            }

            /// <summary>
            /// The ProductItem_div item.
            /// </summary>
            [RepositoryItem("2d770580-0b3a-4636-a9e7-aba8fc7dd3ee")]
            public virtual Ranorex.DivTag ProductItem_div
            {
                get
                {
                    return _productitem_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductItem_div item info.
            /// </summary>
            [RepositoryItemInfo("2d770580-0b3a-4636-a9e7-aba8fc7dd3ee")]
            public virtual RepoItemInfo ProductItem_divInfo
            {
                get
                {
                    return _productitem_divInfo;
                }
            }

            /// <summary>
            /// The ProductImg_div item.
            /// </summary>
            [RepositoryItem("a40ac1b0-2323-4827-a924-6984842ec2f6")]
            public virtual Ranorex.ImgTag ProductImg_div
            {
                get
                {
                    return _productimg_divInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ProductImg_div item info.
            /// </summary>
            [RepositoryItemInfo("a40ac1b0-2323-4827-a924-6984842ec2f6")]
            public virtual RepoItemInfo ProductImg_divInfo
            {
                get
                {
                    return _productimg_divInfo;
                }
            }

            /// <summary>
            /// The ProductName_div item.
            /// </summary>
            [RepositoryItem("53d93c6b-8cf2-45f7-b30c-64ccceb2e320")]
            public virtual Ranorex.DivTag ProductName_div
            {
                get
                {
                    return _productname_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductName_div item info.
            /// </summary>
            [RepositoryItemInfo("53d93c6b-8cf2-45f7-b30c-64ccceb2e320")]
            public virtual RepoItemInfo ProductName_divInfo
            {
                get
                {
                    return _productname_divInfo;
                }
            }

            /// <summary>
            /// The ProductDescritpion_div item.
            /// </summary>
            [RepositoryItem("f6220996-0c38-4d0b-8270-d98dd595cf00")]
            public virtual Ranorex.DivTag ProductDescritpion_div
            {
                get
                {
                    return _productdescritpion_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductDescritpion_div item info.
            /// </summary>
            [RepositoryItemInfo("f6220996-0c38-4d0b-8270-d98dd595cf00")]
            public virtual RepoItemInfo ProductDescritpion_divInfo
            {
                get
                {
                    return _productdescritpion_divInfo;
                }
            }

            /// <summary>
            /// The ProductPrice_div item.
            /// </summary>
            [RepositoryItem("5f65492b-294f-44e3-9b43-64a427f324f8")]
            public virtual Ranorex.DivTag ProductPrice_div
            {
                get
                {
                    return _productprice_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductPrice_div item info.
            /// </summary>
            [RepositoryItemInfo("5f65492b-294f-44e3-9b43-64a427f324f8")]
            public virtual RepoItemInfo ProductPrice_divInfo
            {
                get
                {
                    return _productprice_divInfo;
                }
            }

            /// <summary>
            /// The AddProduct_btn item.
            /// </summary>
            [RepositoryItem("d203cb1f-3811-4239-ac39-d17a2de11527")]
            public virtual Ranorex.ButtonTag AddProduct_btn
            {
                get
                {
                    return _addproduct_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddProduct_btn item info.
            /// </summary>
            [RepositoryItemInfo("d203cb1f-3811-4239-ac39-d17a2de11527")]
            public virtual RepoItemInfo AddProduct_btnInfo
            {
                get
                {
                    return _addproduct_btnInfo;
                }
            }

            /// <summary>
            /// The numItemsCart_span item.
            /// </summary>
            [RepositoryItem("48083637-a0ad-41ab-b409-3ff520452c5f")]
            public virtual Ranorex.SpanTag numItemsCart_span
            {
                get
                {
                    return _numitemscart_spanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The numItemsCart_span item info.
            /// </summary>
            [RepositoryItemInfo("48083637-a0ad-41ab-b409-3ff520452c5f")]
            public virtual RepoItemInfo numItemsCart_spanInfo
            {
                get
                {
                    return _numitemscart_spanInfo;
                }
            }
        }

        /// <summary>
        /// The CartDetailsFolder folder.
        /// </summary>
        [RepositoryFolder("e069166f-354a-4cdf-a344-eb67520dd19c")]
        public partial class CartDetailsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _yourcart_spanInfo;
            RepoItemInfo _cartitem_divInfo;
            RepoItemInfo _itemname_divInfo;
            RepoItemInfo _itemqyt_divInfo;
            RepoItemInfo _itemdesc_divInfo;
            RepoItemInfo _priceitem_divInfo;
            RepoItemInfo _remove_btnInfo;
            RepoItemInfo _checkout_btnInfo;
            RepoItemInfo _continueshopping_btnInfo;
            RepoItemInfo _fullcart_divInfo;

            /// <summary>
            /// Creates a new CartDetails  folder.
            /// </summary>
            public CartDetailsFolder(RepoGenBaseFolder parentFolder) :
                    base("CartDetails", "", parentFolder, 0, null, false, "e069166f-354a-4cdf-a344-eb67520dd19c", "")
            {
                _yourcart_spanInfo = new RepoItemInfo(this, "YourCart_span", ".//div[#'header_container']/?/?/span[@innertext='Your Cart']", "", 30000, null, "c90ee4c0-3105-4209-b6f5-18fcc646788e");
                _cartitem_divInfo = new RepoItemInfo(this, "CartItem_div", ".//div[#'cart_contents_container']///div[@class='cart_item']", "", 30000, null, "99547111-df18-495e-a2df-5fbd5bfa3052");
                _itemname_divInfo = new RepoItemInfo(this, "itemName_div", ".//div[#'cart_contents_container']///div[@class='inventory_item_name' and @innertext=$productName]", "", 30000, null, "d6274332-1dec-43d0-85d1-595ff0f398dc");
                _itemqyt_divInfo = new RepoItemInfo(this, "itemQyt_div", ".//div[#'cart_contents_container']///div[@class='cart_quantity']", "", 30000, null, "fd79e054-56af-4058-a83a-b6a3d376778a");
                _itemdesc_divInfo = new RepoItemInfo(this, "itemDesc_div", ".//div[#'cart_contents_container']///div[@class='inventory_item_desc']", "", 30000, null, "5b8537bc-13db-4c73-bfd9-c12fb7e17178");
                _priceitem_divInfo = new RepoItemInfo(this, "priceItem_div", ".//div[#'cart_contents_container']///div[@class='inventory_item_price']", "", 30000, null, "cc54b9b2-254a-4ca3-81f9-5b3683defb5d");
                _remove_btnInfo = new RepoItemInfo(this, "Remove_btn", ".//button[@class='btn btn_secondary btn_small cart_button']", "", 30000, null, "3b8368bd-ad10-4b2b-9158-417893292385");
                _checkout_btnInfo = new RepoItemInfo(this, "Checkout_btn", ".//button[#'checkout']", "", 30000, null, "208a00e8-821f-46e9-8040-e9686a0fe6d2");
                _continueshopping_btnInfo = new RepoItemInfo(this, "ContinueShopping_btn", ".//button[#'continue-shopping']", "", 30000, null, "562c70b1-ec9f-47a7-9427-00fc82ae2f76");
                _fullcart_divInfo = new RepoItemInfo(this, "FullCart_div", ".//div[#'contents_wrapper']", "", 30000, null, "135244c8-0157-41f6-8fda-5c5ed8a673d4");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e069166f-354a-4cdf-a344-eb67520dd19c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The YourCart_span item.
            /// </summary>
            [RepositoryItem("c90ee4c0-3105-4209-b6f5-18fcc646788e")]
            public virtual Ranorex.SpanTag YourCart_span
            {
                get
                {
                    return _yourcart_spanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The YourCart_span item info.
            /// </summary>
            [RepositoryItemInfo("c90ee4c0-3105-4209-b6f5-18fcc646788e")]
            public virtual RepoItemInfo YourCart_spanInfo
            {
                get
                {
                    return _yourcart_spanInfo;
                }
            }

            /// <summary>
            /// The CartItem_div item.
            /// </summary>
            [RepositoryItem("99547111-df18-495e-a2df-5fbd5bfa3052")]
            public virtual Ranorex.DivTag CartItem_div
            {
                get
                {
                    return _cartitem_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CartItem_div item info.
            /// </summary>
            [RepositoryItemInfo("99547111-df18-495e-a2df-5fbd5bfa3052")]
            public virtual RepoItemInfo CartItem_divInfo
            {
                get
                {
                    return _cartitem_divInfo;
                }
            }

            /// <summary>
            /// The itemName_div item.
            /// </summary>
            [RepositoryItem("d6274332-1dec-43d0-85d1-595ff0f398dc")]
            public virtual Ranorex.DivTag itemName_div
            {
                get
                {
                    return _itemname_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The itemName_div item info.
            /// </summary>
            [RepositoryItemInfo("d6274332-1dec-43d0-85d1-595ff0f398dc")]
            public virtual RepoItemInfo itemName_divInfo
            {
                get
                {
                    return _itemname_divInfo;
                }
            }

            /// <summary>
            /// The itemQyt_div item.
            /// </summary>
            [RepositoryItem("fd79e054-56af-4058-a83a-b6a3d376778a")]
            public virtual Ranorex.DivTag itemQyt_div
            {
                get
                {
                    return _itemqyt_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The itemQyt_div item info.
            /// </summary>
            [RepositoryItemInfo("fd79e054-56af-4058-a83a-b6a3d376778a")]
            public virtual RepoItemInfo itemQyt_divInfo
            {
                get
                {
                    return _itemqyt_divInfo;
                }
            }

            /// <summary>
            /// The itemDesc_div item.
            /// </summary>
            [RepositoryItem("5b8537bc-13db-4c73-bfd9-c12fb7e17178")]
            public virtual Ranorex.DivTag itemDesc_div
            {
                get
                {
                    return _itemdesc_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The itemDesc_div item info.
            /// </summary>
            [RepositoryItemInfo("5b8537bc-13db-4c73-bfd9-c12fb7e17178")]
            public virtual RepoItemInfo itemDesc_divInfo
            {
                get
                {
                    return _itemdesc_divInfo;
                }
            }

            /// <summary>
            /// The priceItem_div item.
            /// </summary>
            [RepositoryItem("cc54b9b2-254a-4ca3-81f9-5b3683defb5d")]
            public virtual Ranorex.DivTag priceItem_div
            {
                get
                {
                    return _priceitem_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The priceItem_div item info.
            /// </summary>
            [RepositoryItemInfo("cc54b9b2-254a-4ca3-81f9-5b3683defb5d")]
            public virtual RepoItemInfo priceItem_divInfo
            {
                get
                {
                    return _priceitem_divInfo;
                }
            }

            /// <summary>
            /// The Remove_btn item.
            /// </summary>
            [RepositoryItem("3b8368bd-ad10-4b2b-9158-417893292385")]
            public virtual Ranorex.ButtonTag Remove_btn
            {
                get
                {
                    return _remove_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Remove_btn item info.
            /// </summary>
            [RepositoryItemInfo("3b8368bd-ad10-4b2b-9158-417893292385")]
            public virtual RepoItemInfo Remove_btnInfo
            {
                get
                {
                    return _remove_btnInfo;
                }
            }

            /// <summary>
            /// The Checkout_btn item.
            /// </summary>
            [RepositoryItem("208a00e8-821f-46e9-8040-e9686a0fe6d2")]
            public virtual Ranorex.ButtonTag Checkout_btn
            {
                get
                {
                    return _checkout_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Checkout_btn item info.
            /// </summary>
            [RepositoryItemInfo("208a00e8-821f-46e9-8040-e9686a0fe6d2")]
            public virtual RepoItemInfo Checkout_btnInfo
            {
                get
                {
                    return _checkout_btnInfo;
                }
            }

            /// <summary>
            /// The ContinueShopping_btn item.
            /// </summary>
            [RepositoryItem("562c70b1-ec9f-47a7-9427-00fc82ae2f76")]
            public virtual Ranorex.ButtonTag ContinueShopping_btn
            {
                get
                {
                    return _continueshopping_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ContinueShopping_btn item info.
            /// </summary>
            [RepositoryItemInfo("562c70b1-ec9f-47a7-9427-00fc82ae2f76")]
            public virtual RepoItemInfo ContinueShopping_btnInfo
            {
                get
                {
                    return _continueshopping_btnInfo;
                }
            }

            /// <summary>
            /// The FullCart_div item.
            /// </summary>
            [RepositoryItem("135244c8-0157-41f6-8fda-5c5ed8a673d4")]
            public virtual Ranorex.DivTag FullCart_div
            {
                get
                {
                    return _fullcart_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FullCart_div item info.
            /// </summary>
            [RepositoryItemInfo("135244c8-0157-41f6-8fda-5c5ed8a673d4")]
            public virtual RepoItemInfo FullCart_divInfo
            {
                get
                {
                    return _fullcart_divInfo;
                }
            }
        }

        /// <summary>
        /// The CheckoutFolder folder.
        /// </summary>
        [RepositoryFolder("aa4b8b25-7c5f-4372-8c69-49a5757459d0")]
        public partial class CheckoutFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkoutyourinformation_spanInfo;
            RepoItemInfo _firstname_inputInfo;
            RepoItemInfo _lastname_inputInfo;
            RepoItemInfo _postalcode_inputInfo;
            RepoItemInfo _cancel_btnInfo;
            RepoItemInfo _continue_btnInfo;
            RepoItemInfo _checkoutinformation_divInfo;

            /// <summary>
            /// Creates a new Checkout  folder.
            /// </summary>
            public CheckoutFolder(RepoGenBaseFolder parentFolder) :
                    base("Checkout", "", parentFolder, 0, null, false, "aa4b8b25-7c5f-4372-8c69-49a5757459d0", "")
            {
                _checkoutyourinformation_spanInfo = new RepoItemInfo(this, "CheckoutYourInformation_span", ".//div[#'header_container']/?/?/span[@innertext>'Checkout: Your Informatio']", "", 30000, null, "fa271586-5df4-4a3b-af7c-e8c61d309fb3");
                _firstname_inputInfo = new RepoItemInfo(this, "FirstName_input", ".//input[#'first-name']", "", 30000, null, "c34f645f-e01a-446b-850d-f85d6be4bfa2");
                _lastname_inputInfo = new RepoItemInfo(this, "LastName_input", ".//input[#'last-name']", "", 30000, null, "25141b13-537b-48d9-bd24-b0b7c0c1976f");
                _postalcode_inputInfo = new RepoItemInfo(this, "PostalCode_input", ".//input[#'postal-code']", "", 30000, null, "e9964036-2209-48e3-a776-9f8bd806a5db");
                _cancel_btnInfo = new RepoItemInfo(this, "Cancel_btn", ".//button[#'cancel']", "", 30000, null, "c803eed8-bfd5-4eb9-9fb5-17515af70c40");
                _continue_btnInfo = new RepoItemInfo(this, "Continue_btn", ".//input[#'continue']", "", 30000, null, "9f438f55-243f-4807-94f4-a21df551b66e");
                _checkoutinformation_divInfo = new RepoItemInfo(this, "CheckoutInformation_div", ".//div[#'checkout_info_container']/?/?/form[@action='https://www.saucedemo.com/checkout-step-one.html']/div[1]", "", 30000, null, "5cad0d46-7105-4bae-8252-b32f5dc20da4");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa4b8b25-7c5f-4372-8c69-49a5757459d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckoutYourInformation_span item.
            /// </summary>
            [RepositoryItem("fa271586-5df4-4a3b-af7c-e8c61d309fb3")]
            public virtual Ranorex.SpanTag CheckoutYourInformation_span
            {
                get
                {
                    return _checkoutyourinformation_spanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutYourInformation_span item info.
            /// </summary>
            [RepositoryItemInfo("fa271586-5df4-4a3b-af7c-e8c61d309fb3")]
            public virtual RepoItemInfo CheckoutYourInformation_spanInfo
            {
                get
                {
                    return _checkoutyourinformation_spanInfo;
                }
            }

            /// <summary>
            /// The FirstName_input item.
            /// </summary>
            [RepositoryItem("c34f645f-e01a-446b-850d-f85d6be4bfa2")]
            public virtual Ranorex.InputTag FirstName_input
            {
                get
                {
                    return _firstname_inputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName_input item info.
            /// </summary>
            [RepositoryItemInfo("c34f645f-e01a-446b-850d-f85d6be4bfa2")]
            public virtual RepoItemInfo FirstName_inputInfo
            {
                get
                {
                    return _firstname_inputInfo;
                }
            }

            /// <summary>
            /// The LastName_input item.
            /// </summary>
            [RepositoryItem("25141b13-537b-48d9-bd24-b0b7c0c1976f")]
            public virtual Ranorex.InputTag LastName_input
            {
                get
                {
                    return _lastname_inputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName_input item info.
            /// </summary>
            [RepositoryItemInfo("25141b13-537b-48d9-bd24-b0b7c0c1976f")]
            public virtual RepoItemInfo LastName_inputInfo
            {
                get
                {
                    return _lastname_inputInfo;
                }
            }

            /// <summary>
            /// The PostalCode_input item.
            /// </summary>
            [RepositoryItem("e9964036-2209-48e3-a776-9f8bd806a5db")]
            public virtual Ranorex.InputTag PostalCode_input
            {
                get
                {
                    return _postalcode_inputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PostalCode_input item info.
            /// </summary>
            [RepositoryItemInfo("e9964036-2209-48e3-a776-9f8bd806a5db")]
            public virtual RepoItemInfo PostalCode_inputInfo
            {
                get
                {
                    return _postalcode_inputInfo;
                }
            }

            /// <summary>
            /// The Cancel_btn item.
            /// </summary>
            [RepositoryItem("c803eed8-bfd5-4eb9-9fb5-17515af70c40")]
            public virtual Ranorex.ButtonTag Cancel_btn
            {
                get
                {
                    return _cancel_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Cancel_btn item info.
            /// </summary>
            [RepositoryItemInfo("c803eed8-bfd5-4eb9-9fb5-17515af70c40")]
            public virtual RepoItemInfo Cancel_btnInfo
            {
                get
                {
                    return _cancel_btnInfo;
                }
            }

            /// <summary>
            /// The Continue_btn item.
            /// </summary>
            [RepositoryItem("9f438f55-243f-4807-94f4-a21df551b66e")]
            public virtual Ranorex.InputTag Continue_btn
            {
                get
                {
                    return _continue_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Continue_btn item info.
            /// </summary>
            [RepositoryItemInfo("9f438f55-243f-4807-94f4-a21df551b66e")]
            public virtual RepoItemInfo Continue_btnInfo
            {
                get
                {
                    return _continue_btnInfo;
                }
            }

            /// <summary>
            /// The CheckoutInformation_div item.
            /// </summary>
            [RepositoryItem("5cad0d46-7105-4bae-8252-b32f5dc20da4")]
            public virtual Ranorex.DivTag CheckoutInformation_div
            {
                get
                {
                    return _checkoutinformation_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutInformation_div item info.
            /// </summary>
            [RepositoryItemInfo("5cad0d46-7105-4bae-8252-b32f5dc20da4")]
            public virtual RepoItemInfo CheckoutInformation_divInfo
            {
                get
                {
                    return _checkoutinformation_divInfo;
                }
            }
        }

        /// <summary>
        /// The OverviewFolder folder.
        /// </summary>
        [RepositoryFolder("fb868e7e-32ac-434d-b394-6b9591dbea1d")]
        public partial class OverviewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _totalamt_divInfo;
            RepoItemInfo _taxdollar240_divInfo;
            RepoItemInfo _shippinginfo_divInfo;
            RepoItemInfo _totaltotalamt_divInfo;
            RepoItemInfo _finish_btnInfo;
            RepoItemInfo _checkoutoverview_spanInfo;

            /// <summary>
            /// Creates a new Overview  folder.
            /// </summary>
            public OverviewFolder(RepoGenBaseFolder parentFolder) :
                    base("Overview", "", parentFolder, 0, null, false, "fb868e7e-32ac-434d-b394-6b9591dbea1d", "")
            {
                _totalamt_divInfo = new RepoItemInfo(this, "totalAmt_div", ".//div[#'checkout_summary_container']//div[@innertext~'Item total: ']", "", 30000, null, "c91e032f-a27d-43f7-b08b-b16ae0e9fdd2");
                _taxdollar240_divInfo = new RepoItemInfo(this, "TaxDollar240_div", ".//div[#'checkout_summary_container']//div[@innertext~'Tax: ']", "", 30000, null, "c2774fc9-ffdb-4cab-9b7d-dc3752b9c74a");
                _shippinginfo_divInfo = new RepoItemInfo(this, "shippingInfo_div", ".//div[#'checkout_summary_container']//div[@innertext>'FREE PONY EXPRESS DELIVER']", "", 30000, null, "deec2ca9-5bf5-4d5f-8ddb-9703db7adf7f");
                _totaltotalamt_divInfo = new RepoItemInfo(this, "totalTotalAmt_div", ".//div[#'checkout_summary_container']//div[@innertext~'Total: ']", "", 30000, null, "2ba9e43b-71bb-469d-a39f-85f8ebd6bc42");
                _finish_btnInfo = new RepoItemInfo(this, "Finish_btn", ".//button[#'finish']", "", 30000, null, "c66b2077-19b0-47b7-9e2b-6cfb5a886f3a");
                _checkoutoverview_spanInfo = new RepoItemInfo(this, "CheckoutOverview_span", ".//div[#'header_container']/?/?/span[@innertext='Checkout: Overview']", "", 30000, null, "7a1002db-ca4d-4919-99c8-1109939225fd");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fb868e7e-32ac-434d-b394-6b9591dbea1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The totalAmt_div item.
            /// </summary>
            [RepositoryItem("c91e032f-a27d-43f7-b08b-b16ae0e9fdd2")]
            public virtual Ranorex.DivTag totalAmt_div
            {
                get
                {
                    return _totalamt_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The totalAmt_div item info.
            /// </summary>
            [RepositoryItemInfo("c91e032f-a27d-43f7-b08b-b16ae0e9fdd2")]
            public virtual RepoItemInfo totalAmt_divInfo
            {
                get
                {
                    return _totalamt_divInfo;
                }
            }

            /// <summary>
            /// The TaxDollar240_div item.
            /// </summary>
            [RepositoryItem("c2774fc9-ffdb-4cab-9b7d-dc3752b9c74a")]
            public virtual Ranorex.DivTag TaxDollar240_div
            {
                get
                {
                    return _taxdollar240_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The TaxDollar240_div item info.
            /// </summary>
            [RepositoryItemInfo("c2774fc9-ffdb-4cab-9b7d-dc3752b9c74a")]
            public virtual RepoItemInfo TaxDollar240_divInfo
            {
                get
                {
                    return _taxdollar240_divInfo;
                }
            }

            /// <summary>
            /// The shippingInfo_div item.
            /// </summary>
            [RepositoryItem("deec2ca9-5bf5-4d5f-8ddb-9703db7adf7f")]
            public virtual Ranorex.DivTag shippingInfo_div
            {
                get
                {
                    return _shippinginfo_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The shippingInfo_div item info.
            /// </summary>
            [RepositoryItemInfo("deec2ca9-5bf5-4d5f-8ddb-9703db7adf7f")]
            public virtual RepoItemInfo shippingInfo_divInfo
            {
                get
                {
                    return _shippinginfo_divInfo;
                }
            }

            /// <summary>
            /// The totalTotalAmt_div item.
            /// </summary>
            [RepositoryItem("2ba9e43b-71bb-469d-a39f-85f8ebd6bc42")]
            public virtual Ranorex.DivTag totalTotalAmt_div
            {
                get
                {
                    return _totaltotalamt_divInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The totalTotalAmt_div item info.
            /// </summary>
            [RepositoryItemInfo("2ba9e43b-71bb-469d-a39f-85f8ebd6bc42")]
            public virtual RepoItemInfo totalTotalAmt_divInfo
            {
                get
                {
                    return _totaltotalamt_divInfo;
                }
            }

            /// <summary>
            /// The Finish_btn item.
            /// </summary>
            [RepositoryItem("c66b2077-19b0-47b7-9e2b-6cfb5a886f3a")]
            public virtual Ranorex.ButtonTag Finish_btn
            {
                get
                {
                    return _finish_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Finish_btn item info.
            /// </summary>
            [RepositoryItemInfo("c66b2077-19b0-47b7-9e2b-6cfb5a886f3a")]
            public virtual RepoItemInfo Finish_btnInfo
            {
                get
                {
                    return _finish_btnInfo;
                }
            }

            /// <summary>
            /// The CheckoutOverview_span item.
            /// </summary>
            [RepositoryItem("7a1002db-ca4d-4919-99c8-1109939225fd")]
            public virtual Ranorex.SpanTag CheckoutOverview_span
            {
                get
                {
                    return _checkoutoverview_spanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutOverview_span item info.
            /// </summary>
            [RepositoryItemInfo("7a1002db-ca4d-4919-99c8-1109939225fd")]
            public virtual RepoItemInfo CheckoutOverview_spanInfo
            {
                get
                {
                    return _checkoutoverview_spanInfo;
                }
            }
        }

        /// <summary>
        /// The PurchaseDoneFolder folder.
        /// </summary>
        [RepositoryFolder("7012e882-544c-4626-9eb3-0c3dd9361468")]
        public partial class PurchaseDoneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkoutcomplete_spanInfo;
            RepoItemInfo _thanksorder_titleInfo;
            RepoItemInfo _backtoproducts_btnInfo;

            /// <summary>
            /// Creates a new PurchaseDone  folder.
            /// </summary>
            public PurchaseDoneFolder(RepoGenBaseFolder parentFolder) :
                    base("PurchaseDone", "", parentFolder, 0, null, false, "7012e882-544c-4626-9eb3-0c3dd9361468", "")
            {
                _checkoutcomplete_spanInfo = new RepoItemInfo(this, "CheckoutComplete_span", ".//div[#'header_container']/?/?/span[@innertext='Checkout: Complete!']", "", 30000, null, "330bb083-7fc1-47f6-a53b-9206a0c5a1bc");
                _thanksorder_titleInfo = new RepoItemInfo(this, "ThanksOrder_title", ".//div[#'checkout_complete_container']/h2[@innertext='THANK YOU FOR YOUR ORDER']", "", 30000, null, "cedef74f-9a79-4be4-81d5-748a2a857f77");
                _backtoproducts_btnInfo = new RepoItemInfo(this, "BackToProducts_btn", ".//button[#'back-to-products']", "", 30000, null, "c0269c42-c3ef-4470-87ee-7fa3b8ff713e");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7012e882-544c-4626-9eb3-0c3dd9361468")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CheckoutComplete_span item.
            /// </summary>
            [RepositoryItem("330bb083-7fc1-47f6-a53b-9206a0c5a1bc")]
            public virtual Ranorex.SpanTag CheckoutComplete_span
            {
                get
                {
                    return _checkoutcomplete_spanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutComplete_span item info.
            /// </summary>
            [RepositoryItemInfo("330bb083-7fc1-47f6-a53b-9206a0c5a1bc")]
            public virtual RepoItemInfo CheckoutComplete_spanInfo
            {
                get
                {
                    return _checkoutcomplete_spanInfo;
                }
            }

            /// <summary>
            /// The ThanksOrder_title item.
            /// </summary>
            [RepositoryItem("cedef74f-9a79-4be4-81d5-748a2a857f77")]
            public virtual Ranorex.H2Tag ThanksOrder_title
            {
                get
                {
                    return _thanksorder_titleInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The ThanksOrder_title item info.
            /// </summary>
            [RepositoryItemInfo("cedef74f-9a79-4be4-81d5-748a2a857f77")]
            public virtual RepoItemInfo ThanksOrder_titleInfo
            {
                get
                {
                    return _thanksorder_titleInfo;
                }
            }

            /// <summary>
            /// The BackToProducts_btn item.
            /// </summary>
            [RepositoryItem("c0269c42-c3ef-4470-87ee-7fa3b8ff713e")]
            public virtual Ranorex.ButtonTag BackToProducts_btn
            {
                get
                {
                    return _backtoproducts_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BackToProducts_btn item info.
            /// </summary>
            [RepositoryItemInfo("c0269c42-c3ef-4470-87ee-7fa3b8ff713e")]
            public virtual RepoItemInfo BackToProducts_btnInfo
            {
                get
                {
                    return _backtoproducts_btnInfo;
                }
            }
        }

        /// <summary>
        /// The MenuFolder folder.
        /// </summary>
        [RepositoryFolder("6eb37da9-ff55-4cb7-8f83-420516acd984")]
        public partial class MenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _allitems_menu_linkInfo;
            RepoItemInfo _about_menu_linkInfo;
            RepoItemInfo _logout_menu_linkInfo;
            RepoItemInfo _reset_menu_linkInfo;
            RepoItemInfo _close_menu_btnInfo;

            /// <summary>
            /// Creates a new Menu  folder.
            /// </summary>
            public MenuFolder(RepoGenBaseFolder parentFolder) :
                    base("Menu", "", parentFolder, 0, null, false, "6eb37da9-ff55-4cb7-8f83-420516acd984", "")
            {
                _allitems_menu_linkInfo = new RepoItemInfo(this, "AllItems_menu_link", ".//a[#'inventory_sidebar_link']", "", 30000, null, "4c1c49a9-ae8d-4145-b516-6a937433b835");
                _about_menu_linkInfo = new RepoItemInfo(this, "About_menu_link", ".//a[#'about_sidebar_link']", "", 30000, null, "dc53bc4a-4ddd-4d68-8fff-8c4899fb3d45");
                _logout_menu_linkInfo = new RepoItemInfo(this, "Logout_menu_link", ".//a[#'logout_sidebar_link']", "", 30000, null, "5286e07a-b742-4850-bb26-ecf929620f1b");
                _reset_menu_linkInfo = new RepoItemInfo(this, "Reset_menu_link", ".//a[#'reset_sidebar_link']", "", 30000, null, "b23c92af-1362-4245-a5a4-801730a4c345");
                _close_menu_btnInfo = new RepoItemInfo(this, "Close_menu_btn", ".//button[#'react-burger-cross-btn']", "", 30000, null, "2a788a92-7598-48ac-9e24-bd593c4f5a43");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6eb37da9-ff55-4cb7-8f83-420516acd984")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AllItems_menu_link item.
            /// </summary>
            [RepositoryItem("4c1c49a9-ae8d-4145-b516-6a937433b835")]
            public virtual Ranorex.ATag AllItems_menu_link
            {
                get
                {
                    return _allitems_menu_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AllItems_menu_link item info.
            /// </summary>
            [RepositoryItemInfo("4c1c49a9-ae8d-4145-b516-6a937433b835")]
            public virtual RepoItemInfo AllItems_menu_linkInfo
            {
                get
                {
                    return _allitems_menu_linkInfo;
                }
            }

            /// <summary>
            /// The About_menu_link item.
            /// </summary>
            [RepositoryItem("dc53bc4a-4ddd-4d68-8fff-8c4899fb3d45")]
            public virtual Ranorex.ATag About_menu_link
            {
                get
                {
                    return _about_menu_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The About_menu_link item info.
            /// </summary>
            [RepositoryItemInfo("dc53bc4a-4ddd-4d68-8fff-8c4899fb3d45")]
            public virtual RepoItemInfo About_menu_linkInfo
            {
                get
                {
                    return _about_menu_linkInfo;
                }
            }

            /// <summary>
            /// The Logout_menu_link item.
            /// </summary>
            [RepositoryItem("5286e07a-b742-4850-bb26-ecf929620f1b")]
            public virtual Ranorex.ATag Logout_menu_link
            {
                get
                {
                    return _logout_menu_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout_menu_link item info.
            /// </summary>
            [RepositoryItemInfo("5286e07a-b742-4850-bb26-ecf929620f1b")]
            public virtual RepoItemInfo Logout_menu_linkInfo
            {
                get
                {
                    return _logout_menu_linkInfo;
                }
            }

            /// <summary>
            /// The Reset_menu_link item.
            /// </summary>
            [RepositoryItem("b23c92af-1362-4245-a5a4-801730a4c345")]
            public virtual Ranorex.ATag Reset_menu_link
            {
                get
                {
                    return _reset_menu_linkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Reset_menu_link item info.
            /// </summary>
            [RepositoryItemInfo("b23c92af-1362-4245-a5a4-801730a4c345")]
            public virtual RepoItemInfo Reset_menu_linkInfo
            {
                get
                {
                    return _reset_menu_linkInfo;
                }
            }

            /// <summary>
            /// The Close_menu_btn item.
            /// </summary>
            [RepositoryItem("2a788a92-7598-48ac-9e24-bd593c4f5a43")]
            public virtual Ranorex.ButtonTag Close_menu_btn
            {
                get
                {
                    return _close_menu_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Close_menu_btn item info.
            /// </summary>
            [RepositoryItemInfo("2a788a92-7598-48ac-9e24-bd593c4f5a43")]
            public virtual RepoItemInfo Close_menu_btnInfo
            {
                get
                {
                    return _close_menu_btnInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
